version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
        - '*'
  - package-ecosystem: "docker"
    directory: "/docker/rdf2hdt/"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
        - '*'
    ignore:
      - dependency-name: "alpine"
